# Generated by Django 5.0.1 on 2024-02-15 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_dummyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.authenfaceuser'),
        ),
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.authenfaceuser'),
        ),
    ]
