# Generated by Django 5.0.2 on 2024-03-15 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_snapshot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenfaceuser',
            name='userImageName',
        ),
        migrations.AddField(
            model_name='authenfaceuser',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='snapshots/'),
            preserve_default=False,
        ),
    ]
