# Generated by Django 5.0.1 on 2024-01-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenFaceSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenfaceuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
