# Generated by Django 5.0.1 on 2024-01-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenFaceSite', '0002_alter_authenfaceuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='imageName',
            new_name='name',
        ),
    ]
