# Generated by Django 5.0.1 on 2024-01-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenFaceSite', '0005_rename_snapshots_snapshot_rename_websites_website_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='accountName',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
