# Generated by Django 5.0.1 on 2024-01-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenFaceSite', '0006_rename_createdat_snapshot_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
