# Generated by Django 5.0.1 on 2024-01-27 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenFaceUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AuthenFaceSite.authenfaceuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageName', models.CharField(max_length=50)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AuthenFaceSite.authenfaceuser')),
            ],
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('accountName', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AuthenFaceSite.authenfaceuser')),
            ],
        ),
    ]
