# Generated by Django 5.0.1 on 2024-01-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenFaceSite', '0003_rename_imagename_userimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenfaceuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='snapshots',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='websites',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
